#!/usr/bin/env python3
"""Train final judge router model and export weights as Rust constants.

Reads combined_features.tsv, trains LogisticRegression on all trainable rows,
and outputs src/judge_weights.rs with:
  - SCALER_MEAN: [f64; N]
  - SCALER_SCALE: [f64; N]
  - COEF: [[f64; N]; 4]   (4 classes × N features)
  - INTERCEPT: [f64; 4]
  - FEATURE_NAMES: [&str; N]  (for debugging)
  - THRESHOLD: f64

Usage:
  python3 scripts/export_weights.py bench/combined_features.tsv
"""

import sys
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


THRESHOLD = 0.65  # from Round 6 analysis: best trade-off GS+BB+GZ


def main():
    if len(sys.argv) < 2:
        print("Usage: export_weights.py <combined_features.tsv>")
        sys.exit(1)

    df = pd.read_csv(sys.argv[1], sep="\t")
    print(f"Loaded {len(df)} rows")

    # Drop unfixable
    df = df[df["label"] != -1].reset_index(drop=True)
    print(f"Trainable: {len(df)}")

    # Feature columns: drop identifiers, absolute BPMs, and phrase features
    # (phrase features require librosa beat tracker + chroma not yet ported to Rust)
    drop_cols = [
        "track_id", "dataset", "gt_bpm", "label",
        "det_bpm", "ioi_bpm", "comb_bpm", "ac_bpm", "lowac_bpm", "hopf_bpm", "spec_bpm",
        "bpm_librosa",
        "mode",
        # Phrase probe features (not available in Rust yet)
        "n_beats", "best_shift", "best_score", "prominence",
        "is_ternary_top", "is_edm_phrase_top",
        "sim_1", "sim_2", "sim_3", "sim_4", "sim_6", "sim_8", "sim_12", "sim_16", "sim_32",
    ]
    feature_cols = []
    for c in df.columns:
        if c in drop_cols:
            continue
        try:
            df[c].astype(float)
            feature_cols.append(c)
        except (ValueError, TypeError):
            print(f"  (skipping non-numeric: {c})")

    print(f"Features: {len(feature_cols)}")
    for i, f in enumerate(feature_cols):
        print(f"  [{i:2d}] {f}")

    X = df[feature_cols].values.astype(np.float64)
    y = df["label"].values.astype(np.int64)
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

    # Fit scaler
    scaler = StandardScaler().fit(X)
    Xs = scaler.transform(X)

    # Train final model
    clf = LogisticRegression(solver="lbfgs", max_iter=2000, C=1.0)
    clf.fit(Xs, y)
    print(f"\nTraining accuracy: {clf.score(Xs, y)*100:.1f}%")
    print(f"Classes: {clf.classes_}")

    # Verify class order is [0, 1, 2, 3]
    assert list(clf.classes_) == [0, 1, 2, 3], f"Unexpected class order: {clf.classes_}"

    n_features = len(feature_cols)
    n_classes = 4

    # Sanity checks
    assert clf.coef_.shape == (n_classes, n_features), f"coef shape: {clf.coef_.shape}"
    assert clf.intercept_.shape == (n_classes,), f"intercept shape: {clf.intercept_.shape}"
    assert scaler.mean_.shape == (n_features,)
    assert scaler.scale_.shape == (n_features,)

    # Generate Rust source
    out_path = "src/judge_weights.rs"
    with open(out_path, "w") as f:
        f.write("//! Auto-generated judge router weights.\n")
        f.write("//!\n")
        f.write(f"//! Trained on {len(df)} rows from GiantSteps + Ballroom + GTZAN.\n")
        f.write(f"//! {n_features} features, {n_classes} classes (0=keep, 1=halve, 2=double, 3=triple).\n")
        f.write(f"//! Training accuracy: {clf.score(Xs, y)*100:.1f}%\n")
        f.write("//!\n")
        f.write("//! Generated by scripts/export_weights.py -- do not edit manually.\n\n")

        f.write(f"/// Number of features expected by the router.\n")
        f.write(f"pub const N_FEATURES: usize = {n_features};\n\n")

        f.write(f"/// Number of output classes.\n")
        f.write(f"pub const N_CLASSES: usize = {n_classes};\n\n")

        f.write(f"/// Threshold: only override class 0 if P(best non-zero class) > THRESHOLD.\n")
        f.write(f"pub const THRESHOLD: f64 = {THRESHOLD};\n\n")

        # Feature names
        f.write("/// Feature names (for debugging; matches the order of SCALER_MEAN etc.).\n")
        f.write("pub const FEATURE_NAMES: [&str; N_FEATURES] = [\n")
        for name in feature_cols:
            f.write(f'    "{name}",\n')
        f.write("];\n\n")

        # Scaler mean
        f.write("/// StandardScaler mean (subtract before scaling).\n")
        f.write("pub const SCALER_MEAN: [f64; N_FEATURES] = [\n")
        for v in scaler.mean_:
            f.write(f"    {v:.12e},\n")
        f.write("];\n\n")

        # Scaler scale
        f.write("/// StandardScaler scale (divide after centering).\n")
        f.write("pub const SCALER_SCALE: [f64; N_FEATURES] = [\n")
        for v in scaler.scale_:
            f.write(f"    {v:.12e},\n")
        f.write("];\n\n")

        # Coefficients: [n_classes][n_features]
        f.write("/// Logistic regression coefficients: COEF[class][feature].\n")
        f.write("pub const COEF: [[f64; N_FEATURES]; N_CLASSES] = [\n")
        for cls_idx in range(n_classes):
            f.write("    // class {}: {}\n".format(
                cls_idx,
                {0: "keep", 1: "halve", 2: "double", 3: "triple"}[cls_idx]
            ))
            f.write("    [\n")
            for feat_idx in range(n_features):
                f.write(f"        {clf.coef_[cls_idx, feat_idx]:.12e},  // {feature_cols[feat_idx]}\n")
            f.write("    ],\n")
        f.write("];\n\n")

        # Intercepts
        f.write("/// Logistic regression intercepts (one per class).\n")
        f.write("pub const INTERCEPT: [f64; N_CLASSES] = [\n")
        for cls_idx in range(n_classes):
            f.write(f"    {clf.intercept_[cls_idx]:.12e},  // class {cls_idx}\n")
        f.write("];\n")

    print(f"\nWrote {out_path}")
    print(f"  {n_features} features × {n_classes} classes")
    print(f"  Total numbers: {n_features * n_classes + n_classes + 2 * n_features} "
          f"(coef={n_features * n_classes}, intercept={n_classes}, scaler={2 * n_features})")


if __name__ == "__main__":
    main()
