//! Auto-generated judge router weights.
//!
//! Trained on 1951 rows from GiantSteps + Ballroom + GTZAN.
//! 32 features, 4 classes (0=keep, 1=halve, 2=double, 3=triple).
//! Training accuracy: 82.4%
//!
//! Generated by scripts/export_weights.py -- do not edit manually.

/// Number of features expected by the router.
pub const N_FEATURES: usize = 32;

/// Number of output classes.
pub const N_CLASSES: usize = 4;

/// Threshold: only override class 0 if P(best non-zero class) > THRESHOLD.
pub const THRESHOLD: f64 = 0.65;

/// Feature names (for debugging; matches the order of SCALER_MEAN etc.).
pub const FEATURE_NAMES: [&str; N_FEATURES] = [
    "det_conf",
    "ioi_conf",
    "comb_conf",
    "ac_conf",
    "lowac_conf",
    "hopf_conf",
    "spec_conf",
    "crest_db",
    "transient_density",
    "tempo_stability",
    "d_low",
    "d_high",
    "machine_timed",
    "drumless",
    "duration_s",
    "n_onsets",
    "pc_det",
    "pc_half",
    "pc_double",
    "pc_triple",
    "es_det",
    "es_half",
    "es_double",
    "es_triple",
    "me_det",
    "me_half",
    "me_double",
    "me_triple",
    "io_det",
    "io_half",
    "io_double",
    "io_triple",
];

/// StandardScaler mean (subtract before scaling).
pub const SCALER_MEAN: [f64; N_FEATURES] = [
    5.825868272681e-01,
    4.346232701179e-02,
    4.242047667863e-01,
    6.525269605331e-01,
    7.225559712968e-01,
    1.294878523834e-01,
    7.376008200923e-01,
    1.338362890825e+01,
    7.970773962071e+00,
    1.062588416197e-02,
    6.355130702204e+00,
    5.479302921579e+00,
    0.000000000000e+00,
    0.000000000000e+00,
    5.455004613019e+01,
    4.623311122501e+02,
    7.287380830343e-02,
    4.584859046643e-02,
    2.561698616094e-01,
    1.063596617119e-01,
    5.054892362891e-01,
    4.721828293183e-01,
    6.839991799077e-01,
    5.014988723731e-01,
    4.590800615069e-01,
    4.324934392619e-01,
    6.743632496156e-01,
    5.683962070733e-01,
    6.406661199385e-01,
    2.362822142491e-01,
    7.816861609431e-01,
    6.154704766786e-01,
];

/// StandardScaler scale (divide after centering).
pub const SCALER_SCALE: [f64; N_FEATURES] = [
    1.123373317755e-01,
    2.719776049283e-02,
    1.325572345959e-01,
    1.809815492518e-01,
    1.917661830552e-01,
    5.703628464693e-02,
    1.002477327597e-01,
    2.432020009407e+00,
    1.409890946653e+00,
    6.032999370857e-02,
    1.111830685827e+00,
    8.491196188410e-01,
    1.000000000000e+00,
    1.000000000000e+00,
    3.964672471948e+01,
    3.905242465399e+02,
    6.306906488905e-02,
    3.029757484229e-02,
    2.037257898788e-01,
    1.137788057384e-01,
    2.372591533541e-01,
    2.384164723492e-01,
    2.054775012142e-01,
    9.767824852292e-02,
    1.941422567756e-01,
    1.968113707633e-01,
    1.720747413017e-01,
    1.436447793714e-01,
    1.621682802767e-01,
    1.862481769581e-01,
    1.102403270636e-01,
    1.614869160619e-01,
];

/// Logistic regression coefficients: COEF[class][feature].
pub const COEF: [[f64; N_FEATURES]; N_CLASSES] = [
    // class 0: keep
    [
        7.606696924506e-02,  // det_conf
        2.258816808953e-01,  // ioi_conf
        1.222274740045e-01,  // comb_conf
        -2.728714044023e-01,  // ac_conf
        5.640011359788e-02,  // lowac_conf
        -1.240402835523e-01,  // hopf_conf
        2.050654782884e-01,  // spec_conf
        1.456792596872e-02,  // crest_db
        1.728476080330e-01,  // transient_density
        1.459905443657e-01,  // tempo_stability
        1.015555938554e-01,  // d_low
        7.468363909028e-02,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        2.528718558228e-01,  // duration_s
        2.009224572733e-01,  // n_onsets
        4.214053810642e-01,  // pc_det
        1.952994221785e-02,  // pc_half
        -4.298297017960e-01,  // pc_double
        4.459789452631e-01,  // pc_triple
        -4.277181351341e-02,  // es_det
        -1.429192200376e-03,  // es_half
        3.646797709513e-01,  // es_double
        -2.808090899414e-01,  // es_triple
        -2.606070827600e-01,  // me_det
        -7.374485184329e-02,  // me_half
        1.927369975957e-01,  // me_double
        -3.242461045370e-03,  // me_triple
        6.853845933245e-01,  // io_det
        2.432124512871e-02,  // io_half
        4.714402862433e-01,  // io_double
        -4.103147087263e-01,  // io_triple
    ],
    // class 1: halve
    [
        1.659166342541e-01,  // det_conf
        9.260979087378e-02,  // ioi_conf
        7.056080822858e-01,  // comb_conf
        -1.759195075141e-01,  // ac_conf
        1.222499366820e-02,  // lowac_conf
        -1.935070948206e-01,  // hopf_conf
        -1.118033946233e-01,  // spec_conf
        -9.673378387840e-02,  // crest_db
        1.777072754055e+00,  // transient_density
        -2.750205658994e-02,  // tempo_stability
        -3.530112426255e-01,  // d_low
        -4.086877691339e-01,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        5.180069422799e-01,  // duration_s
        -5.549780626261e-01,  // n_onsets
        -3.277426490039e-01,  // pc_det
        2.163722449675e-01,  // pc_half
        1.456599265284e-01,  // pc_double
        1.386292445830e-01,  // pc_triple
        -1.618420486463e-02,  // es_det
        1.770643759758e-01,  // es_half
        -4.752582994283e-01,  // es_double
        1.158344640046e-01,  // es_triple
        9.278820288130e-02,  // me_det
        -1.714123310281e-01,  // me_half
        4.167921880940e-01,  // me_double
        1.691696670579e-01,  // me_triple
        1.373632348554e+00,  // io_det
        1.814331788191e+00,  // io_half
        4.051312349900e-01,  // io_double
        7.542444755548e-01,  // io_triple
    ],
    // class 2: double
    [
        -2.820425409912e-01,  // det_conf
        4.785363729892e-02,  // ioi_conf
        -1.729524950637e-01,  // comb_conf
        3.369773747038e-01,  // ac_conf
        -5.245037646310e-02,  // lowac_conf
        -2.909900853756e-01,  // hopf_conf
        -3.420447573566e-02,  // spec_conf
        9.310985408498e-02,  // crest_db
        -1.662620683573e+00,  // transient_density
        -7.902787103681e-02,  // tempo_stability
        5.504035687517e-01,  // d_low
        -3.637564689991e-02,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        -3.492929918559e-01,  // duration_s
        8.011763300729e-01,  // n_onsets
        6.558910621244e-01,  // pc_det
        -2.746456643033e-01,  // pc_half
        8.454252744835e-01,  // pc_double
        -1.054487058202e+00,  // pc_triple
        -7.386232576426e-02,  // es_det
        -2.120462287317e-02,  // es_half
        2.745665779102e-01,  // es_double
        1.051287257619e-01,  // es_triple
        -1.561009423527e-02,  // me_det
        5.949570289968e-02,  // me_half
        -2.038622384639e-01,  // me_double
        -4.699864179047e-01,  // me_triple
        -1.934027332717e-01,  // io_det
        -1.805797778485e+00,  // io_half
        3.608684923360e-01,  // io_double
        -5.034011997683e-01,  // io_triple
    ],
    // class 3: triple
    [
        4.005893749203e-02,  // det_conf
        -3.663451090680e-01,  // ioi_conf
        -6.548830612266e-01,  // comb_conf
        1.118135372125e-01,  // ac_conf
        -1.617473080301e-02,  // lowac_conf
        6.085374637485e-01,  // hopf_conf
        -5.905760792940e-02,  // spec_conf
        -1.094399617529e-02,  // crest_db
        -2.872996785151e-01,  // transient_density
        -3.946061673890e-02,  // tempo_stability
        -2.989479199816e-01,  // d_low
        3.703797769435e-01,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        -4.215858062469e-01,  // duration_s
        -4.471207247201e-01,  // n_onsets
        -7.495537941847e-01,  // pc_det
        3.874347711799e-02,  // pc_half
        -5.612554992160e-01,  // pc_double
        4.698788683555e-01,  // pc_triple
        1.328183441423e-01,  // es_det
        -1.544305609022e-01,  // es_half
        -1.639880494332e-01,  // es_double
        5.984590017493e-02,  // es_triple
        1.834289741139e-01,  // me_det
        1.856614799717e-01,  // me_half
        -4.056669472258e-01,  // me_double
        3.040592118922e-01,  // me_triple
        -1.865614208607e+00,  // io_det
        -3.285525483490e-02,  // io_half
        -1.237440013569e+00,  // io_double
        1.594714329398e-01,  // io_triple
    ],
];

/// Logistic regression intercepts (one per class).
pub const INTERCEPT: [f64; N_CLASSES] = [
    5.544510967528e+00,  // class 0
    2.527527711953e+00,  // class 1
    1.090912272156e+00,  // class 2
    -9.162950951637e+00,  // class 3
];
