//! Judge router: learned post-fusion BPM correction.
//!
//! A multinomial logistic regression trained on GiantSteps + Ballroom + GTZAN
//! (1951 tracks) predicts whether the fused BPM should be kept, halved,
//! doubled, or tripled based on 47 features extracted from the pipeline.
//!
//! The router only fires when it is confident in a non-zero class
//! (P > THRESHOLD). Otherwise the original fused BPM is preserved.
//!
//! Zero external dependencies -- all weights are compile-time constants
//! generated by `scripts/export_weights.py`.

use crate::judge_weights::*;
use crate::onset::Onset;
use crate::tempo;
use crate::TempoEstimate;

/// Router decision: what to do with the fused BPM.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum RouterDecision {
    /// Class 0: keep the fused BPM as-is.
    Keep,
    /// Class 1: halve the fused BPM (detected was 2× the true BPM).
    Halve,
    /// Class 2: double the fused BPM (detected was 0.5× the true BPM).
    Double,
    /// Class 3: triple the fused BPM (detected was 1/3× the true BPM).
    Triple,
}

impl RouterDecision {
    /// The BPM multiplier for this decision.
    pub fn multiplier(self) -> f64 {
        match self {
            RouterDecision::Keep => 1.0,
            RouterDecision::Halve => 0.5,
            RouterDecision::Double => 2.0,
            RouterDecision::Triple => 3.0,
        }
    }
}

/// Features needed by the router, extracted from the pipeline.
///
/// The 47 features must be in exactly the order listed in
/// `judge_weights::FEATURE_NAMES`. This struct provides a safe builder
/// that constructs the feature vector from pipeline components.
pub struct RouterFeatures {
    values: [f64; N_FEATURES],
}

impl RouterFeatures {
    /// Build the feature vector from pipeline outputs.
    ///
    /// # Arguments
    /// * `det_bpm` - Final detected BPM (after fusion + resolve_metrical)
    /// * `det_conf` - Final confidence
    /// * `estimators` - Per-estimator results
    /// * `passport` - Acoustic passport
    /// * `onsets` - Detected onsets
    /// * `duration` - Track duration in seconds
    /// * `phrase_features` - Optional phrase probe features (if None, zeros used)
    pub fn build(
        det_conf: f64,
        estimators: &crate::EstimatorResults,
        passport: &crate::bouncer::AcousticPassport,
        onsets: &[Onset],
        det_bpm: f64,
        duration: f64,
        phrase_features: Option<&PhraseFeatures>,
    ) -> Self {
        let est_val = |e: Option<TempoEstimate>| -> (f64, f64) {
            e.map(|e| (e.bpm, e.confidence)).unwrap_or((0.0, 0.0))
        };

        let (_ioi_bpm, ioi_conf) = est_val(estimators.ioi);
        let (_comb_bpm, comb_conf) = est_val(estimators.comb);
        let (_ac_bpm, ac_conf) = est_val(estimators.autocorrelation);
        let (_lowac_bpm, lowac_conf) = est_val(estimators.low_band_ac);
        let (_hopf_bpm, hopf_conf) = est_val(estimators.hopf);
        let (_spec_bpm, spec_conf) = est_val(estimators.spectral);

        // Candidates for Round 3 metrics
        let candidates = [det_bpm, det_bpm / 2.0, det_bpm * 2.0, det_bpm * 3.0];

        let pc: Vec<f64> = candidates.iter().map(|&c| tempo::phase_coherence_r(onsets, c)).collect();
        let es: Vec<f64> = candidates.iter().map(|&c| tempo::empty_slot_score(onsets, c, duration)).collect();
        let me: Vec<f64> = candidates.iter().map(|&c| tempo::median_energy_ratio_score(onsets, c)).collect();
        let io: Vec<f64> = candidates.iter().map(|&c| tempo::ioi_multiple_score(onsets, c)).collect();

        // Phrase features: use provided or zeros
        let pf = phrase_features.cloned().unwrap_or_default();

        let mut values = [0.0f64; N_FEATURES];
        // Order MUST match FEATURE_NAMES in judge_weights.rs
        values[0] = det_conf;
        values[1] = ioi_conf;
        values[2] = comb_conf;
        values[3] = ac_conf;
        values[4] = lowac_conf;
        values[5] = hopf_conf;
        values[6] = spec_conf;
        values[7] = passport.crest_factor_db as f64;
        values[8] = passport.transient_density as f64;
        values[9] = passport.tempo_stability as f64;
        values[10] = passport.d_low as f64;
        values[11] = passport.d_high as f64;
        values[12] = if passport.is_machine_timed { 1.0 } else { 0.0 };
        values[13] = if passport.is_drumless { 1.0 } else { 0.0 };
        values[14] = duration;
        values[15] = onsets.len() as f64;
        // Round 3 metrics: pc, es, me, io at det/half/double/triple
        values[16] = pc[0]; values[17] = pc[1]; values[18] = pc[2]; values[19] = pc[3];
        values[20] = es[0]; values[21] = es[1]; values[22] = es[2]; values[23] = es[3];
        values[24] = me[0]; values[25] = me[1]; values[26] = me[2]; values[27] = me[3];
        values[28] = io[0]; values[29] = io[1]; values[30] = io[2]; values[31] = io[3];
        // Phrase features [32..46]
        values[32] = pf.n_beats;
        values[33] = pf.best_shift;
        values[34] = pf.best_score;
        values[35] = pf.prominence;
        values[36] = pf.is_ternary_top;
        values[37] = pf.is_edm_phrase_top;
        values[38] = pf.sim_1;
        values[39] = pf.sim_2;
        values[40] = pf.sim_3;
        values[41] = pf.sim_4;
        values[42] = pf.sim_6;
        values[43] = pf.sim_8;
        values[44] = pf.sim_12;
        values[45] = pf.sim_16;
        values[46] = pf.sim_32;

        Self { values }
    }
}

/// Phrase probe features (computed externally, optional).
/// If not provided, zeros are used (the classifier still works using
/// the other 32 features -- `prominence` is the only phrase-exclusive
/// feature in the top-8 for the "halve" class).
#[derive(Debug, Clone)]
pub struct PhraseFeatures {
    pub n_beats: f64,
    pub best_shift: f64,
    pub best_score: f64,
    pub prominence: f64,
    pub is_ternary_top: f64,
    pub is_edm_phrase_top: f64,
    pub sim_1: f64,
    pub sim_2: f64,
    pub sim_3: f64,
    pub sim_4: f64,
    pub sim_6: f64,
    pub sim_8: f64,
    pub sim_12: f64,
    pub sim_16: f64,
    pub sim_32: f64,
}

impl Default for PhraseFeatures {
    fn default() -> Self {
        Self {
            n_beats: 0.0, best_shift: 0.0, best_score: 0.0,
            prominence: 0.0, is_ternary_top: 0.0, is_edm_phrase_top: 0.0,
            sim_1: 0.0, sim_2: 0.0, sim_3: 0.0, sim_4: 0.0, sim_6: 0.0,
            sim_8: 0.0, sim_12: 0.0, sim_16: 0.0, sim_32: 0.0,
        }
    }
}

/// Run the judge router: predict whether to keep/halve/double/triple the BPM.
///
/// Returns `Keep` if the router is not confident enough in any correction
/// (probability of the best non-zero class <= THRESHOLD).
pub fn apply_router(features: &RouterFeatures) -> RouterDecision {
    // 1. Standardize features: z = (x - mean) / scale
    let mut z = [0.0f64; N_FEATURES];
    for i in 0..N_FEATURES {
        let scale = SCALER_SCALE[i];
        if scale.abs() > 1e-15 {
            z[i] = (features.values[i] - SCALER_MEAN[i]) / scale;
        }
    }

    // 2. Compute logits: logit[c] = intercept[c] + sum(coef[c][i] * z[i])
    let mut logits = [0.0f64; N_CLASSES];
    for c in 0..N_CLASSES {
        logits[c] = INTERCEPT[c];
        for i in 0..N_FEATURES {
            logits[c] += COEF[c][i] * z[i];
        }
    }

    // 3. Softmax: P[c] = exp(logit[c]) / sum(exp(logit[c']))
    let max_logit = logits.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let mut exp_logits = [0.0f64; N_CLASSES];
    let mut sum_exp = 0.0f64;
    for c in 0..N_CLASSES {
        exp_logits[c] = (logits[c] - max_logit).exp();
        sum_exp += exp_logits[c];
    }
    let mut probs = [0.0f64; N_CLASSES];
    for c in 0..N_CLASSES {
        probs[c] = exp_logits[c] / sum_exp;
    }

    // 4. Threshold gating: only override "keep" if a non-zero class
    //    has probability above THRESHOLD.
    let mut best_nonzero_class = 1usize;
    let mut best_nonzero_prob = probs[1];
    for c in 2..N_CLASSES {
        if probs[c] > best_nonzero_prob {
            best_nonzero_prob = probs[c];
            best_nonzero_class = c;
        }
    }

    if best_nonzero_prob > THRESHOLD {
        match best_nonzero_class {
            1 => RouterDecision::Halve,
            2 => RouterDecision::Double,
            3 => RouterDecision::Triple,
            _ => RouterDecision::Keep,
        }
    } else {
        RouterDecision::Keep
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_router_produces_valid_decision() {
        // All-zero features: the model still produces a valid decision
        // (which class wins depends on the interaction of intercepts
        // with the scaler centering -- not necessarily "keep").
        let features = RouterFeatures { values: [0.0; N_FEATURES] };
        let decision = apply_router(&features);
        // Just verify it's one of the valid decisions
        assert!(matches!(
            decision,
            RouterDecision::Keep | RouterDecision::Halve | RouterDecision::Double | RouterDecision::Triple
        ));
    }

    #[test]
    fn test_multiplier() {
        assert_eq!(RouterDecision::Keep.multiplier(), 1.0);
        assert_eq!(RouterDecision::Halve.multiplier(), 0.5);
        assert_eq!(RouterDecision::Double.multiplier(), 2.0);
        assert_eq!(RouterDecision::Triple.multiplier(), 3.0);
    }
}
