//! Judge router: learned post-fusion BPM correction.
//!
//! A multinomial logistic regression trained on GiantSteps + Ballroom + GTZAN
//! (1951 tracks) predicts whether the fused BPM should be kept, halved,
//! doubled, or tripled based on 32 features extracted from the pipeline.
//!
//! The training used 47 features (including 15 phrase probe features from
//! librosa beat tracking + chromagram analysis), but the Rust deployment
//! uses only the 32 features computable in pure Rust. The phrase features
//! were dropped because porting librosa's beat tracker and CQT chromagram
//! is non-trivial. The 32-feature model achieves +102 tracks in cross-
//! validation vs +143 for the full 47-feature model.
//!
//! The router only fires when it is confident in a non-zero class
//! (P > THRESHOLD). Otherwise the original fused BPM is preserved.
//!
//! Zero external dependencies -- all weights are compile-time constants
//! generated by `scripts/export_weights.py`.

use crate::judge_weights::*;
use crate::onset::Onset;
use crate::tempo;
use crate::TempoEstimate;

/// Router decision: what to do with the fused BPM.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum RouterDecision {
    /// Class 0: keep the fused BPM as-is.
    Keep,
    /// Class 1: halve the fused BPM (detected was 2× the true BPM).
    Halve,
    /// Class 2: double the fused BPM (detected was 0.5× the true BPM).
    Double,
    /// Class 3: triple the fused BPM (detected was 1/3× the true BPM).
    Triple,
}

impl RouterDecision {
    /// The BPM multiplier for this decision.
    pub fn multiplier(self) -> f64 {
        match self {
            RouterDecision::Keep => 1.0,
            RouterDecision::Halve => 0.5,
            RouterDecision::Double => 2.0,
            RouterDecision::Triple => 3.0,
        }
    }
}

/// Features needed by the router, extracted from the pipeline.
///
/// The 32 features must be in exactly the order listed in
/// `judge_weights::FEATURE_NAMES`. This struct provides a safe builder
/// that constructs the feature vector from pipeline components.
pub struct RouterFeatures {
    values: [f64; N_FEATURES],
}

impl RouterFeatures {
    /// Build the 32-element feature vector from pipeline outputs.
    ///
    /// All features are computable in pure Rust (no phrase probe / librosa needed).
    pub fn build(
        det_conf: f64,
        estimators: &crate::EstimatorResults,
        passport: &crate::bouncer::AcousticPassport,
        onsets: &[Onset],
        det_bpm: f64,
        duration: f64,
    ) -> Self {
        let est_val = |e: Option<TempoEstimate>| -> (f64, f64) {
            e.map(|e| (e.bpm, e.confidence)).unwrap_or((0.0, 0.0))
        };

        let (_ioi_bpm, ioi_conf) = est_val(estimators.ioi);
        let (_comb_bpm, comb_conf) = est_val(estimators.comb);
        let (_ac_bpm, ac_conf) = est_val(estimators.autocorrelation);
        let (_lowac_bpm, lowac_conf) = est_val(estimators.low_band_ac);
        let (_hopf_bpm, hopf_conf) = est_val(estimators.hopf);
        let (_spec_bpm, spec_conf) = est_val(estimators.spectral);

        // Candidates for Round 3 metrics
        let candidates = [det_bpm, det_bpm / 2.0, det_bpm * 2.0, det_bpm * 3.0];

        let pc: Vec<f64> = candidates.iter().map(|&c| tempo::phase_coherence_r(onsets, c)).collect();
        let es: Vec<f64> = candidates.iter().map(|&c| tempo::empty_slot_score(onsets, c, duration)).collect();
        let me: Vec<f64> = candidates.iter().map(|&c| tempo::median_energy_ratio_score(onsets, c)).collect();
        let io: Vec<f64> = candidates.iter().map(|&c| tempo::ioi_multiple_score(onsets, c)).collect();

        let mut values = [0.0f64; N_FEATURES];
        // Order MUST match FEATURE_NAMES in judge_weights.rs
        values[0] = det_conf;
        values[1] = ioi_conf;
        values[2] = comb_conf;
        values[3] = ac_conf;
        values[4] = lowac_conf;
        values[5] = hopf_conf;
        values[6] = spec_conf;
        values[7] = passport.crest_factor_db as f64;
        values[8] = passport.transient_density as f64;
        values[9] = passport.tempo_stability as f64;
        values[10] = passport.d_low as f64;
        values[11] = passport.d_high as f64;
        values[12] = if passport.is_machine_timed { 1.0 } else { 0.0 };
        values[13] = if passport.is_drumless { 1.0 } else { 0.0 };
        values[14] = duration;
        values[15] = onsets.len() as f64;
        // Round 3 metrics: pc, es, me, io at det/half/double/triple
        values[16] = pc[0]; values[17] = pc[1]; values[18] = pc[2]; values[19] = pc[3];
        values[20] = es[0]; values[21] = es[1]; values[22] = es[2]; values[23] = es[3];
        values[24] = me[0]; values[25] = me[1]; values[26] = me[2]; values[27] = me[3];
        values[28] = io[0]; values[29] = io[1]; values[30] = io[2]; values[31] = io[3];

        Self { values }
    }
}

/// Run the judge router: predict whether to keep/halve/double/triple the BPM.
///
/// Returns `Keep` if the router is not confident enough in any correction
/// (probability of the best non-zero class <= THRESHOLD).
pub fn apply_router(features: &RouterFeatures) -> RouterDecision {
    // 1. Standardize features: z = (x - mean) / scale
    let mut z = [0.0f64; N_FEATURES];
    for i in 0..N_FEATURES {
        let scale = SCALER_SCALE[i];
        if scale.abs() > 1e-15 {
            z[i] = (features.values[i] - SCALER_MEAN[i]) / scale;
        }
    }

    // 2. Compute logits: logit[c] = intercept[c] + sum(coef[c][i] * z[i])
    let mut logits = [0.0f64; N_CLASSES];
    for c in 0..N_CLASSES {
        logits[c] = INTERCEPT[c];
        for i in 0..N_FEATURES {
            logits[c] += COEF[c][i] * z[i];
        }
    }

    // 3. Softmax: P[c] = exp(logit[c]) / sum(exp(logit[c']))
    let max_logit = logits.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let mut exp_logits = [0.0f64; N_CLASSES];
    let mut sum_exp = 0.0f64;
    for c in 0..N_CLASSES {
        exp_logits[c] = (logits[c] - max_logit).exp();
        sum_exp += exp_logits[c];
    }
    let mut probs = [0.0f64; N_CLASSES];
    for c in 0..N_CLASSES {
        probs[c] = exp_logits[c] / sum_exp;
    }

    // 4. Threshold gating: only override "keep" if a non-zero class
    //    has probability above THRESHOLD.
    let mut best_nonzero_class = 1usize;
    let mut best_nonzero_prob = probs[1];
    for (c, &p) in probs.iter().enumerate().skip(2) {
        if p > best_nonzero_prob {
            best_nonzero_prob = p;
            best_nonzero_class = c;
        }
    }

    // DEBUG: uncomment to trace router decisions
    // eprintln!("ROUTER: probs=[{:.3},{:.3},{:.3},{:.3}] best_nz=class{} p={:.3} -> {}",
    //     probs[0], probs[1], probs[2], probs[3],
    //     best_nonzero_class, best_nonzero_prob,
    //     if best_nonzero_prob > THRESHOLD { "OVERRIDE" } else { "keep" });

    if best_nonzero_prob > THRESHOLD {
        match best_nonzero_class {
            1 => RouterDecision::Halve,
            2 => RouterDecision::Double,
            3 => RouterDecision::Triple,
            _ => RouterDecision::Keep,
        }
    } else {
        RouterDecision::Keep
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_router_produces_valid_decision() {
        // All-zero features: the model still produces a valid decision
        // (which class wins depends on the interaction of intercepts
        // with the scaler centering -- not necessarily "keep").
        let features = RouterFeatures { values: [0.0; N_FEATURES] };
        let decision = apply_router(&features);
        // Just verify it's one of the valid decisions
        assert!(matches!(
            decision,
            RouterDecision::Keep | RouterDecision::Halve | RouterDecision::Double | RouterDecision::Triple
        ));
    }

    #[test]
    fn test_multiplier() {
        assert_eq!(RouterDecision::Keep.multiplier(), 1.0);
        assert_eq!(RouterDecision::Halve.multiplier(), 0.5);
        assert_eq!(RouterDecision::Double.multiplier(), 2.0);
        assert_eq!(RouterDecision::Triple.multiplier(), 3.0);
    }
}
