//! Auto-generated judge router weights.
//!
//! Trained on 1951 rows from GiantSteps + Ballroom + GTZAN.
//! 47 features, 4 classes (0=keep, 1=halve, 2=double, 3=triple).
//! Training accuracy: 85.2%
//!
//! Generated by scripts/export_weights.py -- do not edit manually.

/// Number of features expected by the router.
pub const N_FEATURES: usize = 47;

/// Number of output classes.
pub const N_CLASSES: usize = 4;

/// Threshold: only override class 0 if P(best non-zero class) > THRESHOLD.
pub const THRESHOLD: f64 = 0.65;

/// Feature names (for debugging; matches the order of SCALER_MEAN etc.).
pub const FEATURE_NAMES: [&str; N_FEATURES] = [
    "det_conf",
    "ioi_conf",
    "comb_conf",
    "ac_conf",
    "lowac_conf",
    "hopf_conf",
    "spec_conf",
    "crest_db",
    "transient_density",
    "tempo_stability",
    "d_low",
    "d_high",
    "machine_timed",
    "drumless",
    "duration_s",
    "n_onsets",
    "pc_det",
    "pc_half",
    "pc_double",
    "pc_triple",
    "es_det",
    "es_half",
    "es_double",
    "es_triple",
    "me_det",
    "me_half",
    "me_double",
    "me_triple",
    "io_det",
    "io_half",
    "io_double",
    "io_triple",
    "n_beats",
    "best_shift",
    "best_score",
    "prominence",
    "is_ternary_top",
    "is_edm_phrase_top",
    "sim_1",
    "sim_2",
    "sim_3",
    "sim_4",
    "sim_6",
    "sim_8",
    "sim_12",
    "sim_16",
    "sim_32",
];

/// StandardScaler mean (subtract before scaling).
pub const SCALER_MEAN: [f64; N_FEATURES] = [
    5.825868272681e-01,
    4.346232701179e-02,
    4.242047667863e-01,
    6.525269605331e-01,
    7.225559712968e-01,
    1.294878523834e-01,
    7.376008200923e-01,
    1.338362890825e+01,
    7.970773962071e+00,
    1.062588416197e-02,
    6.355130702204e+00,
    5.479302921579e+00,
    0.000000000000e+00,
    0.000000000000e+00,
    5.455004613019e+01,
    4.623311122501e+02,
    7.287380830343e-02,
    4.584859046643e-02,
    2.561698616094e-01,
    1.063596617119e-01,
    5.054892362891e-01,
    4.721828293183e-01,
    6.839991799077e-01,
    5.014988723731e-01,
    4.590800615069e-01,
    4.324934392619e-01,
    6.743632496156e-01,
    5.683962070733e-01,
    6.406661199385e-01,
    2.362822142491e-01,
    7.816861609431e-01,
    6.154704766786e-01,
    1.017883136853e+02,
    7.141978472578e+00,
    9.440530358790e-01,
    6.741477191184e-02,
    2.808815991799e-01,
    5.812403895438e-01,
    9.313654079959e-01,
    8.961967616607e-01,
    8.810285079446e-01,
    8.798110697078e-01,
    8.690923669913e-01,
    8.800535064070e-01,
    8.701827678114e-01,
    8.868973147104e-01,
    8.753396104562e-01,
];

/// StandardScaler scale (divide after centering).
pub const SCALER_SCALE: [f64; N_FEATURES] = [
    1.123373317755e-01,
    2.719776049283e-02,
    1.325572345959e-01,
    1.809815492518e-01,
    1.917661830552e-01,
    5.703628464693e-02,
    1.002477327597e-01,
    2.432020009407e+00,
    1.409890946653e+00,
    6.032999370857e-02,
    1.111830685827e+00,
    8.491196188410e-01,
    1.000000000000e+00,
    1.000000000000e+00,
    3.964672471948e+01,
    3.905242465399e+02,
    6.306906488905e-02,
    3.029757484229e-02,
    2.037257898788e-01,
    1.137788057384e-01,
    2.372591533541e-01,
    2.384164723492e-01,
    2.054775012142e-01,
    9.767824852292e-02,
    1.941422567756e-01,
    1.968113707633e-01,
    1.720747413017e-01,
    1.436447793714e-01,
    1.621682802767e-01,
    1.862481769581e-01,
    1.102403270636e-01,
    1.614869160619e-01,
    7.993371027748e+01,
    9.656309950871e+00,
    4.264994775395e-02,
    6.115682962125e-02,
    4.494297791892e-01,
    4.933558544365e-01,
    4.420271868178e-02,
    7.200355209408e-02,
    8.365010047497e-02,
    9.190504312606e-02,
    9.341613493891e-02,
    1.014694480860e-01,
    9.823815263949e-02,
    1.081807508016e-01,
    1.405308390245e-01,
];

/// Logistic regression coefficients: COEF[class][feature].
pub const COEF: [[f64; N_FEATURES]; N_CLASSES] = [
    // class 0: keep
    [
        -1.405818396006e-02,  // det_conf
        2.431869372312e-01,  // ioi_conf
        1.542345306029e-01,  // comb_conf
        -1.775769627432e-01,  // ac_conf
        5.135169165099e-02,  // lowac_conf
        -8.350042641428e-02,  // hopf_conf
        2.597381606889e-01,  // spec_conf
        -1.792444936286e-02,  // crest_db
        1.486001978428e-01,  // transient_density
        1.689165412178e-01,  // tempo_stability
        1.452642746437e-01,  // d_low
        6.856452081411e-02,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        4.650865620405e-02,  // duration_s
        3.987636282286e-01,  // n_onsets
        4.004086672920e-01,  // pc_det
        3.130417401959e-02,  // pc_half
        -4.034276371499e-01,  // pc_double
        4.713842076344e-01,  // pc_triple
        -6.293951110393e-02,  // es_det
        -3.625099554863e-02,  // es_half
        4.197371630713e-01,  // es_double
        -3.472155054381e-01,  // es_triple
        -2.524541124500e-01,  // me_det
        -6.630421596560e-02,  // me_half
        8.013092429424e-02,  // me_double
        8.680595597789e-02,  // me_triple
        7.386328337851e-01,  // io_det
        -6.063723424386e-02,  // io_half
        4.754905077847e-01,  // io_double
        -3.128750066410e-01,  // io_triple
        1.771614693626e-01,  // n_beats
        2.249197700495e-01,  // best_shift
        1.192425318977e-01,  // best_score
        -1.018605090849e-01,  // prominence
        5.274949395381e-02,  // is_ternary_top
        1.155374818452e-01,  // is_edm_phrase_top
        -8.853032854790e-02,  // sim_1
        -1.935209913060e-01,  // sim_2
        -2.962098415691e-01,  // sim_3
        -3.411427661581e-01,  // sim_4
        4.684071758164e-01,  // sim_6
        -3.344244991285e-01,  // sim_8
        1.212530403545e-01,  // sim_12
        -3.369768783043e-02,  // sim_16
        -6.265384301525e-02,  // sim_32
    ],
    // class 1: halve
    [
        1.293762919685e-01,  // det_conf
        8.454497422982e-02,  // ioi_conf
        6.577335377375e-01,  // comb_conf
        -5.333892696374e-02,  // ac_conf
        -1.179555043043e-02,  // lowac_conf
        -1.409980467970e-01,  // hopf_conf
        2.727703049543e-02,  // spec_conf
        -1.197043125024e-01,  // crest_db
        1.639550116564e+00,  // transient_density
        2.529547115351e-02,  // tempo_stability
        -2.580667882101e-01,  // d_low
        -3.626818928600e-01,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        4.971369037220e-01,  // duration_s
        -6.276838467554e-01,  // n_onsets
        -2.671148628505e-01,  // pc_det
        2.369715562551e-01,  // pc_half
        1.404801044825e-01,  // pc_double
        6.223909175855e-02,  // pc_triple
        -1.877441242054e-02,  // es_det
        1.692587487821e-01,  // es_half
        -4.628968278885e-01,  // es_double
        9.072918542860e-02,  // es_triple
        5.893467142266e-02,  // me_det
        -1.641015727354e-01,  // me_half
        3.267778203428e-01,  // me_double
        2.323789221630e-01,  // me_triple
        1.459052436537e+00,  // io_det
        1.801953700481e+00,  // io_half
        4.035509744371e-01,  // io_double
        8.909405537360e-01,  // io_triple
        2.328776637726e-01,  // n_beats
        4.034080912821e-01,  // best_shift
        -9.309380576977e-02,  // best_score
        4.815198639553e-01,  // prominence
        1.069076004847e-01,  // is_ternary_top
        4.050247196096e-01,  // is_edm_phrase_top
        2.147802326284e-01,  // sim_1
        -3.658814245071e-02,  // sim_2
        -1.618603400869e-01,  // sim_3
        7.680012744926e-02,  // sim_4
        -2.208148922721e-01,  // sim_6
        -4.997913883113e-02,  // sim_8
        1.274453010510e-01,  // sim_12
        -1.601912371783e-01,  // sim_16
        -3.244392937089e-01,  // sim_32
    ],
    // class 2: double
    [
        -2.576264651355e-01,  // det_conf
        -7.905398241797e-02,  // ioi_conf
        -4.204090894589e-02,  // comb_conf
        2.918370637547e-01,  // ac_conf
        -1.558159109253e-01,  // lowac_conf
        -2.634296897572e-01,  // hopf_conf
        -2.186964085013e-01,  // spec_conf
        1.030106661900e-01,  // crest_db
        -1.451958823749e+00,  // transient_density
        -1.626091542700e-01,  // tempo_stability
        5.214429845758e-01,  // d_low
        -1.253653327178e-01,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        3.932763581430e-02,  // duration_s
        8.607016574952e-01,  // n_onsets
        6.108996588475e-01,  // pc_det
        -4.077490397076e-01,  // pc_half
        7.256565281985e-01,  // pc_double
        -1.131939351063e+00,  // pc_triple
        -1.092997567075e-01,  // es_det
        6.692162240271e-02,  // es_half
        2.704183596281e-01,  // es_double
        1.917002953690e-01,  // es_triple
        -7.264109831632e-03,  // me_det
        1.820696578429e-03,  // me_half
        -2.313970261725e-01,  // me_double
        -5.249148933464e-01,  // me_triple
        -5.017974347441e-01,  // io_det
        -1.607135071203e+00,  // io_half
        3.880724311549e-01,  // io_double
        -4.526552788605e-01,  // io_triple
        -6.340300834089e-01,  // n_beats
        1.496351981266e-01,  // best_shift
        5.635416330458e-02,  // best_score
        -5.516430382123e-01,  // prominence
        -1.886212428212e-01,  // is_ternary_top
        7.512236821073e-02,  // is_edm_phrase_top
        -4.911487070831e-01,  // sim_1
        1.696840068852e-01,  // sim_2
        5.425173746470e-01,  // sim_3
        1.335879714818e-01,  // sim_4
        -3.734948494580e-01,  // sim_6
        5.756195657450e-02,  // sim_8
        -1.088701761052e-01,  // sim_12
        1.900894069178e-01,  // sim_16
        1.073485829523e-01,  // sim_32
    ],
    // class 3: triple
    [
        1.423083571270e-01,  // det_conf
        -2.486779290431e-01,  // ioi_conf
        -7.699271593946e-01,  // comb_conf
        -6.092117404770e-02,  // ac_conf
        1.162597697048e-01,  // lowac_conf
        4.879281629685e-01,  // hopf_conf
        -6.831878268297e-02,  // spec_conf
        3.461809567521e-02,  // crest_db
        -3.361914906580e-01,  // transient_density
        -3.160285810130e-02,  // tempo_stability
        -4.086404710095e-01,  // d_low
        4.194827047636e-01,  // d_high
        0.000000000000e+00,  // machine_timed
        0.000000000000e+00,  // drumless
        -5.829731957403e-01,  // duration_s
        -6.317814389684e-01,  // n_onsets
        -7.441934632890e-01,  // pc_det
        1.394733094329e-01,  // pc_half
        -4.627089955311e-01,  // pc_double
        5.983160516705e-01,  // pc_triple
        1.910136802319e-01,  // es_det
        -1.999293756361e-01,  // es_half
        -2.272586948110e-01,  // es_double
        6.478602464043e-02,  // es_triple
        2.007835508589e-01,  // me_det
        2.285850921226e-01,  // me_half
        -1.755117184646e-01,  // me_double
        2.057300152055e-01,  // me_triple
        -1.695887835578e+00,  // io_det
        -1.341813950337e-01,  // io_half
        -1.267113913377e+00,  // io_double
        -1.254102682345e-01,  // io_triple
        2.239909502737e-01,  // n_beats
        -7.779630594582e-01,  // best_shift
        -8.250288943250e-02,  // best_score
        1.719836833419e-01,  // prominence
        2.896414838274e-02,  // is_ternary_top
        -5.956845696655e-01,  // is_edm_phrase_top
        3.648988030025e-01,  // sim_1
        6.042512687145e-02,  // sim_2
        -8.444719299109e-02,  // sim_3
        1.307546672270e-01,  // sim_4
        1.259025659136e-01,  // sim_6
        3.268416813852e-01,  // sim_8
        -1.398281653003e-01,  // sim_12
        3.799518090970e-03,  // sim_16
        2.797445537719e-01,  // sim_32
    ],
];

/// Logistic regression intercepts (one per class).
pub const INTERCEPT: [f64; N_CLASSES] = [
    5.473200679113e+00,  // class 0
    2.294542709708e+00,  // class 1
    3.872671453615e-01,  // class 2
    -8.155010534183e+00,  // class 3
];
